package com.example.ui.localization

enum class AppLanguage(val code: String, val displayName: String, val nativeName: String, val flagEmoji: String) {
    BENGALI("bn", "Bengali", "বাংলা", "🇧🇩"),
    ENGLISH("en", "English", "English", "🇺🇸"),
    ARABIC("ar", "Arabic", "العربية", "🇸🇦"),
    GERMAN("de", "German", "Deutsch", "🇩🇪"),
    FRENCH("fr", "French", "Français", "🇫🇷"),
    HINDI("hi", "Hindi", "हिन्दी", "🇮🇳"),
    URDU("ur", "Urdu", "اردو", "🇵🇰"),
    INDONESIAN("id", "Bahasa Indonesia", "Bahasa Indonesia", "🇮🇩");

    companion object {
        fun fromCode(code: String): AppLanguage {
            return entries.find { it.code.equals(code, ignoreCase = true) } ?: ENGLISH
        }
    }
}

data class TranslationStrings(
    val appName: String,
    val home: String,
    val prayerTimes: String,
    val quran: String,
    val sahriIftar: String,
    val tasbih: String,
    val qibla: String,
    val asmaUlHusna: String,
    val duaDhikr: String,
    val islamicVideos: String,
    val liveStream: String,
    val settings: String,
    val nextPrayer: String,
    val currentPrayer: String,
    val remainingTime: String,
    val forbiddenTimes: String,
    val forbiddenNow: String,
    val sunrise: String,
    val zawalNoon: String,
    val sunset: String,
    val fajr: String,
    val dhuhr: String,
    val asr: String,
    val maghrib: String,
    val isha: String,
    val tahajjud: String,
    val ishraq: String,
    val chasht: String,
    val todaySahri: String,
    val todayIftar: String,
    val tomorrowSahri: String,
    val tomorrowIftar: String,
    val sahriEndsIn: String,
    val iftarIn: String,
    val fastingDua: String,
    val iftarDua: String,
    val madhab: String,
    val hanafi: String,
    val shafi: String,
    val calculationMethod: String,
    val hijriAdjustment: String,
    val prayerOffsets: String,
    val language: String,
    val theme: String,
    val darkMode: String,
    val selectLocation: String,
    val useGps: String,
    val division: String,
    val district: String,
    val upazila: String,
    val bangladeshLocations: String,
    val globalCities: String,
    val search: String,
    val searchSurah: String,
    val save: String,
    val cancel: String,
    val continueText: String,
    val getStarted: String,
    val qiblaDirection: String,
    val distanceToKaaba: String,
    val tapToCount: String,
    val reset: String,
    val target: String,
    val namesOfAllahTitle: String,
    val duashisnutitle: String,
    val dailyAyah: String,
    val dailyHadith: String,
    val liveMakkah: String,
    val liveMadinah: String
)

object LocalizedStrings {
    private val english = TranslationStrings(
        appName = "Ibadah",
        home = "Home",
        prayerTimes = "Prayer Times",
        quran = "Al-Quran",
        sahriIftar = "Sahri & Iftar",
        tasbih = "Tasbih",
        qibla = "Qibla",
        asmaUlHusna = "99 Names",
        duaDhikr = "Dua & Dhikr",
        islamicVideos = "Videos",
        liveStream = "Live Stream",
        settings = "Settings",
        nextPrayer = "Next Prayer",
        currentPrayer = "Current Prayer",
        remainingTime = "Remaining",
        forbiddenTimes = "Forbidden Prayer Times",
        forbiddenNow = "Forbidden Time Now",
        sunrise = "Sunrise",
        zawalNoon = "Zawal (Noon)",
        sunset = "Sunset",
        fajr = "Fajr",
        dhuhr = "Dhuhr",
        asr = "Asr",
        maghrib = "Maghrib",
        isha = "Isha",
        tahajjud = "Tahajjud",
        ishraq = "Ishraq",
        chasht = "Chasht (Duha)",
        todaySahri = "Today's Sahri End",
        todayIftar = "Today's Iftar",
        tomorrowSahri = "Tomorrow Sahri",
        tomorrowIftar = "Tomorrow Iftar",
        sahriEndsIn = "Sahri ends in",
        iftarIn = "Iftar in",
        fastingDua = "Dua for Fasting (Niyyah)",
        iftarDua = "Dua for Breaking Fast (Iftar)",
        madhab = "Juristic Method (Madhab)",
        hanafi = "Hanafi",
        shafi = "Shafi'i / Maliki / Hanbali",
        calculationMethod = "Calculation Method",
        hijriAdjustment = "Hijri Date Adjustment",
        prayerOffsets = "Prayer Time Offsets (Minutes)",
        language = "Language",
        theme = "Appearance Theme",
        darkMode = "Dark Mode",
        selectLocation = "Select Location",
        useGps = "Use GPS Auto Detect",
        division = "Division",
        district = "District",
        upazila = "Upazila / Thana",
        bangladeshLocations = "Bangladesh Locations",
        globalCities = "Global Cities",
        search = "Search...",
        searchSurah = "Search Surah by name or meaning...",
        save = "Save",
        cancel = "Cancel",
        continueText = "Continue",
        getStarted = "Get Started",
        qiblaDirection = "Qibla Direction",
        distanceToKaaba = "Distance to Kaaba",
        tapToCount = "Tap anywhere to count",
        reset = "Reset",
        target = "Target",
        namesOfAllahTitle = "99 Beautiful Names of Allah",
        duashisnutitle = "Fortress of the Muslim (Hisnul Muslim)",
        dailyAyah = "Ayah of the Day",
        dailyHadith = "Hadith of the Day",
        liveMakkah = "Makkah 24/7 Live",
        liveMadinah = "Madinah 24/7 Live"
    )

    private val bengali = TranslationStrings(
        appName = "ইবাদাহ",
        home = "হোম",
        prayerTimes = "নামাজের সময়সূচি",
        quran = "আল-কুরআন",
        sahriIftar = "সাহরি ও ইফতার",
        tasbih = "তাসবিহ",
        qibla = "কিবলা কম্পাস",
        asmaUlHusna = "আল্লাহর ৯৯ নাম",
        duaDhikr = "দোয়া ও যিকির",
        islamicVideos = "ভিডিও ও বয়ান",
        liveStream = "লাইভ স্ট্রিম",
        settings = "সেটিংস",
        nextPrayer = "পরবর্তী নামাজ",
        currentPrayer = "বর্তমান ওয়াক্ত",
        remainingTime = "বাকি আছে",
        forbiddenTimes = "নামাজের নিষিদ্ধ সময়",
        forbiddenNow = "এখন নামাজের নিষিদ্ধ সময়",
        sunrise = "সূর্যোদয়",
        zawalNoon = "দুপুরের নিষিদ্ধ সময় (যাওয়াল)",
        sunset = "সূর্যাস্ত",
        fajr = "ফজর",
        dhuhr = "যোহর",
        asr = "আসর",
        maghrib = "মাগরিব",
        isha = "ইশা",
        tahajjud = "তাহাজ্জুদ",
        ishraq = "ইশরাক",
        chasht = "চাশত / দুহা",
        todaySahri = "আজকের সাহরি শেষ",
        todayIftar = "আজকের ইফতার",
        tomorrowSahri = "আগামীকাল সাহরি",
        tomorrowIftar = "আগামীকাল ইফতার",
        sahriEndsIn = "সাহরি শেষ হতে বাকি",
        iftarIn = "ইফতারের বাকি",
        fastingDua = "রোজার নিয়ত",
        iftarDua = "ইফতারের দোয়া",
        madhab = "মাজহাব ও ফিকহ",
        hanafi = "হানাফি",
        shafi = "শাফেয়ী / মালেকী / হাম্বলী",
        calculationMethod = "হিসাবের পদ্ধতি",
        hijriAdjustment = "হিজরি তারিখ সমন্বয়",
        prayerOffsets = "নামাজের সময় সমন্বয় (মিনিট)",
        language = "ভাষা (Language)",
        theme = "থিম / ডার্ক মোড",
        darkMode = "ডার্ক মোড",
        selectLocation = "স্থান নির্বাচন করুন",
        useGps = "স্বয়ংক্রিয় জিপিএস লোকেশন",
        division = "বিভাগ",
        district = "জেলা",
        upazila = "উপজেলা / থানা",
        bangladeshLocations = "বাংলাদেশের জেলা ও উপজেলা",
        globalCities = "বিশ্বের প্রধান শহরসমূহ",
        search = "অনুসন্ধান...",
        searchSurah = "সূরা বা অর্থ অনুসন্ধান করুন...",
        save = "সংরক্ষণ",
        cancel = "বাতিল",
        continueText = "পরবর্তী",
        getStarted = "শুরু করুন",
        qiblaDirection = "কিবলার দিক",
        distanceToKaaba = "কাবা শরিফের দূরত্ব",
        tapToCount = "গণনা করতে যেকোনো স্থানে ট্যাপ করুন",
        reset = "রিসেট",
        target = "টার্গেট",
        namesOfAllahTitle = "আসমাউল হুসনা (আল্লাহর ৯৯টি গুণবাচক নাম)",
        duashisnutitle = "হিসনুল মুসলিম (দৈনন্দিন দোয়া)",
        dailyAyah = "দৈনিক কুরআন আয়াত",
        dailyHadith = "দৈনিক হাদিস",
        liveMakkah = "মক্কা লাইভ সম্প্রচার",
        liveMadinah = "মদিনা লাইভ সম্প্রচার"
    )

    private val arabic = TranslationStrings(
        appName = "عبادة",
        home = "الرئيسية",
        prayerTimes = "مواقيت الصلاة",
        quran = "القرآن الكريم",
        sahriIftar = "السحور والإفطار",
        tasbih = "المسبحة الإلكترونية",
        qibla = "اتجاه القبلة",
        asmaUlHusna = "أسماء الله الحسنى",
        duaDhikr = "الأدعية والأذكار",
        islamicVideos = "مرئيات إسلامية",
        liveStream = "البث المباشر",
        settings = "الإعدادات",
        nextPrayer = "الصلاة القادمة",
        currentPrayer = "الصلاة الحالية",
        remainingTime = "المتبقي",
        forbiddenTimes = "أوقات النهي عن الصلاة",
        forbiddenNow = "وقت كراهة الصلاة الآن",
        sunrise = "الشروق",
        zawalNoon = "وقت الزوال (الظهيرة)",
        sunset = "الغروب",
        fajr = "الفجر",
        dhuhr = "الظهر",
        asr = "العصر",
        maghrib = "المغرب",
        isha = "العشاء",
        tahajjud = "التهجد",
        ishraq = "الإشراق",
        chasht = "الضحى",
        todaySahri = "نهاية السحور اليوم",
        todayIftar = "إفطار اليوم",
        tomorrowSahri = "سحور الغد",
        tomorrowIftar = "إفطار الغد",
        sahriEndsIn = "ينتهي السحور بعد",
        iftarIn = "يحين الإفطار بعد",
        fastingDua = "دعاء نية الصيام",
        iftarDua = "دعاء الإفطار",
        madhab = "المذهب الفقهي",
        hanafi = "حنفي",
        shafi = "شافعي / مالكي / حنبلي",
        calculationMethod = "طريقة الحساب",
        hijriAdjustment = "تعديل التاريخ الهجري",
        prayerOffsets = "فوارق الأوقات (بالدقائق)",
        language = "اللغة",
        theme = "المظهر",
        darkMode = "الوضع الداكن",
        selectLocation = "تحديد الموقع",
        useGps = "تحديد الموقع عبر GPS",
        division = "المنطقة / المقاطعة",
        district = "المدينة",
        upazila = "الحي / المركز",
        bangladeshLocations = "مواقع بنغلاديش",
        globalCities = "مدن العالم",
        search = "بحث...",
        searchSurah = "ابحث عن سورة بالاسم أو المعنى...",
        save = "حفظ",
        cancel = "إلغاء",
        continueText = "متابعة",
        getStarted = "ابدأ الآن",
        qiblaDirection = "اتجاه القبلة",
        distanceToKaaba = "المسافة إلى الكعبة المشرفة",
        tapToCount = "اضغط في أي مكان للعد",
        reset = "إعادة ضبط",
        target = "الهدف",
        namesOfAllahTitle = "أسماء الله الحسنى التسعة والتسعون",
        duashisnutitle = "حصن المسلم من أذكار الكتاب والسنة",
        dailyAyah = "آية اليوم",
        dailyHadith = "حديث اليوم",
        liveMakkah = "بث مكة المكرمة المباشر",
        liveMadinah = "بث المدينة المنورة المباشر"
    )

    private val german = TranslationStrings(
        appName = "Ibadah",
        home = "Startseite",
        prayerTimes = "Gebetszeiten",
        quran = "Al-Quran",
        sahriIftar = "Sahur & Iftar",
        tasbih = "Tasbih",
        qibla = "Qibla-Kompass",
        asmaUlHusna = "99 Namen Allahs",
        duaDhikr = "Dua & Dhikr",
        islamicVideos = "Videos",
        liveStream = "Live-Übertragung",
        settings = "Einstellungen",
        nextPrayer = "Nächstes Gebet",
        currentPrayer = "Aktuelles Gebet",
        remainingTime = "Verbleibend",
        forbiddenTimes = "Verbotene Gebetszeiten",
        forbiddenNow = "Verbotene Gebetszeit Jetzt",
        sunrise = "Sonnenaufgang",
        zawalNoon = "Zawal (Mittag)",
        sunset = "Sonnenuntergang",
        fajr = "Fadschr",
        dhuhr = "Dhuhr",
        asr = "Asr",
        maghrib = "Maghrib",
        isha = "Ischa",
        tahajjud = "Tahadschud",
        ishraq = "Ischraq",
        chasht = "Duha (Chasht)",
        todaySahri = "Sahur-Ende heute",
        todayIftar = "Iftar heute",
        tomorrowSahri = "Sahur morgen",
        tomorrowIftar = "Iftar morgen",
        sahriEndsIn = "Sahur endet in",
        iftarIn = "Iftar in",
        fastingDua = "Fastenabsicht (Niyyah)",
        iftarDua = "Dua zum Fastenbrechen",
        madhab = "Rechtsschule (Madhab)",
        hanafi = "Hanafitisch",
        shafi = "Schafiitisch / Malikitisch / Hanbalitisch",
        calculationMethod = "Berechnungsmethode",
        hijriAdjustment = "Hidschri-Korrektur",
        prayerOffsets = "Gebetszeit-Anpassung (Minuten)",
        language = "Sprache",
        theme = "Erscheinungsbild",
        darkMode = "Dunkelmodus",
        selectLocation = "Standort wählen",
        useGps = "Automatisch per GPS erkennen",
        division = "Region",
        district = "Bezirk",
        upazila = "Gemeinde",
        bangladeshLocations = "Standorte in Bangladesch",
        globalCities = "Weltweite Städte",
        search = "Suchen...",
        searchSurah = "Sure nach Name oder Bedeutung suchen...",
        save = "Speichern",
        cancel = "Abbrechen",
        continueText = "Weiter",
        getStarted = "Loslegen",
        qiblaDirection = "Qibla-Richtung",
        distanceToKaaba = "Entfernung zur Kaaba",
        tapToCount = "Tippen zum Zählen",
        reset = "Zurücksetzen",
        target = "Ziel",
        namesOfAllahTitle = "Die 99 schönsten Namen Allahs",
        duashisnutitle = "Festung des Muslims (Hisnul Muslim)",
        dailyAyah = "Vers des Tages",
        dailyHadith = "Hadith des Tages",
        liveMakkah = "Mekka 24/7 Live",
        liveMadinah = "Medina 24/7 Live"
    )

    private val french = TranslationStrings(
        appName = "Ibadah",
        home = "Accueil",
        prayerTimes = "Heures de Prière",
        quran = "Le Saint Coran",
        sahriIftar = "Sahur & Iftar",
        tasbih = "Chapelet (Tasbih)",
        qibla = "Direction Qibla",
        asmaUlHusna = "99 Noms d'Allah",
        duaDhikr = "Invocations & Dhikr",
        islamicVideos = "Vidéos Islamiques",
        liveStream = "Direct 24/7",
        settings = "Paramètres",
        nextPrayer = "Prochaine Prière",
        currentPrayer = "Prière Actuelle",
        remainingTime = "Temps Restant",
        forbiddenTimes = "Heures Interdites",
        forbiddenNow = "Prière Interdite Actuellement",
        sunrise = "Lever du Soleil",
        zawalNoon = "Zawal (Midi)",
        sunset = "Coucher du Soleil",
        fajr = "Fajr",
        dhuhr = "Dhuhr",
        asr = "Asr",
        maghrib = "Maghrib",
        isha = "Isha",
        tahajjud = "Tahajjud",
        ishraq = "Ishraq",
        chasht = "Chasht / Duha",
        todaySahri = "Fin du Sahur aujourd'hui",
        todayIftar = "Iftar aujourd'hui",
        tomorrowSahri = "Sahur demain",
        tomorrowIftar = "Iftar demain",
        sahriEndsIn = "Fin du Sahur dans",
        iftarIn = "Iftar dans",
        fastingDua = "Intention de Jeûne (Niyyah)",
        iftarDua = "Invocation de Rupture (Iftar)",
        madhab = "École Juridique (Madhab)",
        hanafi = "Hanafite",
        shafi = "Chaféite / Malikite / Hanbalite",
        calculationMethod = "Méthode de Calcul",
        hijriAdjustment = "Ajustement Date Hégirienne",
        prayerOffsets = "Décalage des Prières (min)",
        language = "Langue",
        theme = "Apparence",
        darkMode = "Mode Sombre",
        selectLocation = "Choisir la Ville",
        useGps = "Détection GPS Automatique",
        division = "Région",
        district = "Ville",
        upazila = "Quartier",
        bangladeshLocations = "Villes du Bangladesh",
        globalCities = "Villes Mondiales",
        search = "Rechercher...",
        searchSurah = "Rechercher une sourate...",
        save = "Enregistrer",
        cancel = "Annuler",
        continueText = "Continuer",
        getStarted = "Commencer",
        qiblaDirection = "Direction de la Qibla",
        distanceToKaaba = "Distance à la Kaaba",
        tapToCount = "Appuyez n'importe où pour compter",
        reset = "Réinitialiser",
        target = "Objectif",
        namesOfAllahTitle = "Les 99 Beaux Noms d'Allah",
        duashisnutitle = "La Citadelle du Musulman",
        dailyAyah = "Verset du Jour",
        dailyHadith = "Hadith du Jour",
        liveMakkah = "La Mecque en Direct",
        liveMadinah = "Médine en Direct"
    )

    private val hindi = TranslationStrings(
        appName = "इबादत",
        home = "होम",
        prayerTimes = "नमाज़ के औक़ात",
        quran = "अल-क़ुरआन",
        sahriIftar = "सहरी और इफ़्तार",
        tasbih = "तस्बीह",
        qibla = "क़िबला दिशा",
        asmaUlHusna = "अल्लाह के 99 नाम",
        duaDhikr = "दुआ और ज़िक्र",
        islamicVideos = "इस्लामी वीडियो",
        liveStream = "लाइव प्रसारण",
        settings = "सेटिंग्स",
        nextPrayer = "अगली नमाज़",
        currentPrayer = "वर्तमान नमाज़",
        remainingTime = "बाकी समय",
        forbiddenTimes = "नमाज़ के मकरूह औक़ात",
        forbiddenNow = "अभी नमाज़ का मकरूह वक्त है",
        sunrise = "सूर्योदय (तुलू)",
        zawalNoon = "ज़वाल (दोपहर)",
        sunset = "सूर्यास्त (ग़ुरूब)",
        fajr = "फ़ज्र",
        dhuhr = "ज़ुहर",
        asr = "असर",
        maghrib = "मग़रिब",
        isha = "इशा",
        tahajjud = "तहज्जुद",
        ishraq = "इशराक़",
        chasht = "चाश्त (ज़ुहा)",
        todaySahri = "आज की सहरी ख़त्म",
        todayIftar = "आज का इफ़्तार",
        tomorrowSahri = "कल की सहरी",
        tomorrowIftar = "कल का इफ़्तार",
        sahriEndsIn = "सहरी ख़त्म होने में",
        iftarIn = "इफ़्तार में बाक़ी",
        fastingDua = "रोज़े की नियत",
        iftarDua = "इफ़्तार की दुआ",
        madhab = "मज़हब और फ़िक़्ह",
        hanafi = "हनफ़ी",
        shafi = "शाफ़ई / मालिकी / हनबली",
        calculationMethod = "गणना विधि",
        hijriAdjustment = "हिजरी तारीख समायोजन",
        prayerOffsets = "समय समायोजन (मिनट)",
        language = "भाषा (Language)",
        theme = "थीम",
        darkMode = "डार्क मोड",
        selectLocation = "स्थान चुनें",
        useGps = "जीपीएस ऑटो डिटेक्ट",
        division = "संभाग / राज्य",
        district = "ज़िला",
        upazila = "तहसील / उपज़िला",
        bangladeshLocations = "बांग्लादेश स्थान",
        globalCities = "विश्व के प्रमुख शहर",
        search = "खोजें...",
        searchSurah = "सूरत या अर्थ खोजें...",
        save = "सहेजें",
        cancel = "रद्द करें",
        continueText = "आगे बढ़ें",
        getStarted = "शुरू करें",
        qiblaDirection = "क़िबला की दिशा",
        distanceToKaaba = "काबा से दूरी",
        tapToCount = "गिनने के लिए कहीं भी टैप करें",
        reset = "रीसेट",
        target = "लक्ष्य",
        namesOfAllahTitle = "अस्मा-उल-हुस्ना (अल्लाह के 99 नाम)",
        duashisnutitle = "हिस्नुल मुस्लिम (दुआएं)",
        dailyAyah = "आज की आयत",
        dailyHadith = "आज की हदीस",
        liveMakkah = "मक्का लाइव 24/7",
        liveMadinah = "मदीना लाइव 24/7"
    )

    private val urdu = TranslationStrings(
        appName = "عبادت",
        home = "ہوم",
        prayerTimes = "نماز کے اوقات",
        quran = "القرآن الکریم",
        sahriIftar = "سحری و افطار",
        tasbih = "تسبیح کاؤنٹر",
        qibla = "قبلہ رخ",
        asmaUlHusna = "اسمائے حسنیٰ",
        duaDhikr = "دعائیں اور اذکار",
        islamicVideos = "اسلامی ویڈیوز",
        liveStream = "براہ راست نشریات",
        settings = "ترتیبات (سیٹنگز)",
        nextPrayer = "اگلی نماز",
        currentPrayer = "موجودہ وقت",
        remainingTime = "باقی وقت",
        forbiddenTimes = "ممنوعہ اوقات نماز",
        forbiddenNow = "ابھی نماز کا مکروہ وقت ہے",
        sunrise = "طلوع آفتاب",
        zawalNoon = "زوال (نصف النہار)",
        sunset = "غروب آفتاب",
        fajr = "فجر",
        dhuhr = "ظہر",
        asr = "عصر",
        maghrib = "مغرب",
        isha = "عشاء",
        tahajjud = "تہجد",
        ishraq = "اشراق",
        chasht = "چاشت (ضحیٰ)",
        todaySahri = "آج سحری ختم",
        todayIftar = "آج افطار کا وقت",
        tomorrowSahri = "کل سحری ختم",
        tomorrowIftar = "کل افطار",
        sahriEndsIn = "سحری کا باقی وقت",
        iftarIn = "افطار میں باقی",
        fastingDua = "روزے کی نیت",
        iftarDua = "افطار کی دعا",
        madhab = "فقہی مسلک",
        hanafi = "حنفی",
        shafi = "شافعی / مالکی / حنبلی",
        calculationMethod = "طریقہ حساب",
        hijriAdjustment = "ہجری تاریخ کی ترتیب",
        prayerOffsets = "اوقات نماز میں فرق (منٹ)",
        language = "زبان (Language)",
        theme = "ظاہری شکل (تھیم)",
        darkMode = "ڈارک موڈ",
        selectLocation = "مقام منتخب کریں",
        useGps = "جی پی ایس آٹو لوکیشن",
        division = "ڈویژن / صوبہ",
        district = "ضلع",
        upazila = "تحصیل / تھانہ",
        bangladeshLocations = "بنگلہ دیش کے مقامات",
        globalCities = "دنیا کے اہم شہر",
        search = "تلاش کریں...",
        searchSurah = "سورت یا ترجمہ تلاش کریں...",
        save = "محفوظ کریں",
        cancel = "منسوخ",
        continueText = "آگے بڑھیں",
        getStarted = "شروع کریں",
        qiblaDirection = "قبلہ کا رخ",
        distanceToKaaba = "خانہ کعبہ کا فاصلہ",
        tapToCount = "شمار کرنے کے لیے کہیں بھی چھوئیں",
        reset = "دوبارہ شروع کریں",
        target = "ہدف",
        namesOfAllahTitle = "اسمائے حسنیٰ (اللہ کے 99 نام)",
        duashisnutitle = "حصن المسلم (مسنون دعائیں)",
        dailyAyah = "آج کی قرآنی آیت",
        dailyHadith = "آج کی حدیث",
        liveMakkah = "مکہ مکرمہ لائیو",
        liveMadinah = "مدینہ منورہ لائیو"
    )

    private val indonesian = TranslationStrings(
        appName = "Ibadah",
        home = "Beranda",
        prayerTimes = "Jadwal Sholat",
        quran = "Al-Qur'an",
        sahriIftar = "Sahur & Buka Puasa",
        tasbih = "Tasbih Digital",
        qibla = "Arah Kiblat",
        asmaUlHusna = "99 Asmaul Husna",
        duaDhikr = "Doa & Dzikir",
        islamicVideos = "Video Islami",
        liveStream = "Siaran Langsung",
        settings = "Pengaturan",
        nextPrayer = "Sholat Berikutnya",
        currentPrayer = "Waktu Sholat Sekarang",
        remainingTime = "Sisa Waktu",
        forbiddenTimes = "Waktu Dilarang Sholat",
        forbiddenNow = "Waktu Dilarang Sholat Sekarang",
        sunrise = "Terbit (Syuruq)",
        zawalNoon = "Zawal (Tengah Hari)",
        sunset = "Terbenam",
        fajr = "Subuh",
        dhuhr = "Dzuhur",
        asr = "Ashar",
        maghrib = "Maghrib",
        isha = "Isya",
        tahajjud = "Tahajjud",
        ishraq = "Isyraq",
        chasht = "Dhuha",
        todaySahri = "Batas Sahur Hari Ini",
        todayIftar = "Buka Puasa Hari Ini",
        tomorrowSahri = "Sahur Besok",
        tomorrowIftar = "Buka Puasa Besok",
        sahriEndsIn = "Sahur berakhir dalam",
        iftarIn = "Buka puasa dalam",
        fastingDua = "Niat Puasa",
        iftarDua = "Doa Buka Puasa",
        madhab = "Metode Mazhab",
        hanafi = "Hanafi",
        shafi = "Syafi'i / Maliki / Hambali",
        calculationMethod = "Metode Perhitungan",
        hijriAdjustment = "Penyesuaian Kalender Hijriah",
        prayerOffsets = "Koreksi Waktu Sholat (Menit)",
        language = "Bahasa",
        theme = "Tema Tampilan",
        darkMode = "Mode Gelap",
        selectLocation = "Pilih Lokasi",
        useGps = "Gunakan GPS Otomatis",
        division = "Provinsi",
        district = "Kota / Kabupaten",
        upazila = "Kecamatan",
        bangladeshLocations = "Lokasi Bangladesh",
        globalCities = "Kota-Kota Dunia",
        search = "Cari...",
        searchSurah = "Cari Surah nama atau arti...",
        save = "Simpan",
        cancel = "Batal",
        continueText = "Lanjutkan",
        getStarted = "Mulai",
        qiblaDirection = "Arah Kiblat",
        distanceToKaaba = "Jarak ke Ka'bah",
        tapToCount = "Ketuk di mana saja untuk menghitung",
        reset = "Reset",
        target = "Target",
        namesOfAllahTitle = "99 Asmaul Husna yang Indah",
        duashisnutitle = "Hisnul Muslim (Kumpulan Doa)",
        dailyAyah = "Ayat Hari Ini",
        dailyHadith = "Hadits Hari Ini",
        liveMakkah = "Makkah 24/7 Live",
        liveMadinah = "Madinah 24/7 Live"
    )

    fun get(language: AppLanguage): TranslationStrings {
        return when (language) {
            AppLanguage.BENGALI -> bengali
            AppLanguage.ENGLISH -> english
            AppLanguage.ARABIC -> arabic
            AppLanguage.GERMAN -> german
            AppLanguage.FRENCH -> french
            AppLanguage.HINDI -> hindi
            AppLanguage.URDU -> urdu
            AppLanguage.INDONESIAN -> indonesian
        }
    }
}
